language: java
dist: trusty
sudo: false
install: true

addons:
  sonarcloud:
    organization: "nfinityllc"
    token:
      secure: $SONAR_TOKEN
jdk:
  - oraclejdk8

script:
  - cd codegen
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=nfinityllc_fastcode-codegen

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'