language: java
dist: trusty

addons:
  sonarcloud:
    organization: "nfinityllc"

jdk:
  - oraclejdk8
  
before_install:
- chmod +x mvnw

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  # - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=nfinityllc_fastcode-codegen

  - mvn clean -DskipTests install sonar:sonar -Dsonar.projectKey=nfinityllc_fastcode-codegen -Dsonar.login=${SONAR_TOKEN}

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'